services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  web:
    build:
      context: .
      secrets:
        - master_key
    command: ./bin/thrust ./bin/rails server
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD}@db:5432/pzlabs_website_rails
      RAILS_SERVE_STATIC_FILES: "true"

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

secrets:
  master_key:
    environment: "RAILS_MASTER_KEY"