default: &default
  adapter: postgresql
  encoding: unicode
  # For local development, this pool size is fine
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pzlabs_website_rails_development # Change 'my_app' to your actual app name!

test:
  <<: *default
  database: pzlabs_website_rails_test

production:
  <<: *default
  database: pzlabs_website_rails_production
  username: avfco
  password: <%= ENV["MY_APP_DATABASE_PASSWORD"] %>