default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pzlabs_website_rails_development

test:
  <<: *default
  database: pzlabs_website_rails_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production

  cache:
    <<: *primary_production