default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pzlabs_website_rails_development

test:
  <<: *default
  database: pzlabs_website_rails_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
    port: 5432
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  queue:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
    port: 5432